services:

 redis:
  image: redis:7-alpine
  ports:
   - "6379:6379"
 
 postgres:
  image: postgres:16-alpine
  ports: 
   - "5433:5432"
  environment:
   POSTGRES_USER: ${POSTGRES_USER}
   POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
   POSTGRES_DB: ${POSTGRES_DB}
  volumes:
    - postgres_data:/var/lib/postgresql/data
 
 admin-api: 
  build: ./admin-api
  ports: 
   - "4000:4000"
  depends_on:
    - postgres
    - redis
  environment:
    DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
    REDIS_URL: redis://redis:6379
    JWT_SECRET: ${JWT_SECRET}
  healthcheck:
   test: ["CMD", "node", "-e", "fetch('http://localhost:4000/health').then(() => process.exit(0)).catch(() => process.exit(1))"]
   interval: 5s
   timeout: 3s
   retries: 10
   start_period: 15s


 gateway-core:
  build: ./gateway-core
  ports:
   - "3000:3000"
  depends_on:
    admin-api:
      condition: service_healthy
    redis:
      condition: service_started

  environment:
    REDIS_URL: redis://redis:6379
    ADMIN_API_URL: http://admin-api:4000
    OTEL_EXPORTER_OTLP_ENDPOINT: http://jaeger:4318
    SERVICE_NAME: gateway-core

 jaeger:
  image: jaegertracing/all-in-one:latest
  ports:
    - "16686:16686"   # Jaeger UI
    - "4318:4318"     # OTLP HTTP receiver
  environment:
    COLLECTOR_OTLP_ENABLED: "true"
    
 prometheus:
  image: prom/prometheus:latest
  ports:
    - "9090:9090"
  volumes:
    - ./prometheus.yml:/etc/prometheus/prometheus.yml

volumes:
  postgres_data: