# building the image 
FROM node:18-alpine
WORKDIR /usr/src/app
COPY package*.json ./
RUN npm install

COPY . .
RUN npx prisma generate --schema=./prisma/schema.prisma
RUN npm run build

EXPOSE 4000
CMD [ "node", "dist/index.js" ]